#!/usr/bin/python
import faillog
faillog.printlog("/var/log/system.log", "fail", 3, 5)